-- MySQL Script generated by MySQL Workbench
-- Tue May 23 12:27:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestion_evento
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gestion_evento` ;

-- -----------------------------------------------------
-- Schema gestion_evento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_evento` DEFAULT CHARACTER SET utf8 ;
USE `gestion_evento` ;

-- -----------------------------------------------------
-- Table `gestion_evento`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Empleado` (
  `idEmpleado` INT(10) NOT NULL AUTO_INCREMENT,
  `cedula` BIGINT(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` BIGINT(10) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `tipoEmpleado` ENUM('ADMIN', 'ASESOR', 'AUTO') NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEmpleado_UNIQUE` ON `gestion_evento`.`Empleado` (`idEmpleado` ASC);

CREATE UNIQUE INDEX `cedula_UNIQUE` ON `gestion_evento`.`Empleado` (`cedula` ASC);

CREATE UNIQUE INDEX `telefono_UNIQUE` ON `gestion_evento`.`Empleado` (`telefono` ASC);

CREATE UNIQUE INDEX `correo_UNIQUE` ON `gestion_evento`.`Empleado` (`correo` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Ciudad` (
  `idCiudad` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `gestion_evento`.`Ciudad` (`nombre` ASC);

CREATE UNIQUE INDEX `idCiudad_UNIQUE` ON `gestion_evento`.`Ciudad` (`idCiudad` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Lugar` (
  `idLugar` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `Ciudad_idCiudad` INT(10) NOT NULL,
  PRIMARY KEY (`idLugar`),
  CONSTRAINT `fk_Lugar_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `gestion_evento`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idLugar_UNIQUE` ON `gestion_evento`.`Lugar` (`idLugar` ASC);

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `gestion_evento`.`Lugar` (`nombre` ASC);

CREATE INDEX `fk_Lugar_Ciudad1_idx` ON `gestion_evento`.`Lugar` (`Ciudad_idCiudad` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Evento` (
  `idEvento` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `fechaFin` DATE NOT NULL,
  `horaFin` TIME NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `costo` DOUBLE NOT NULL,
  `estado` ENUM('Por iniciar', 'En curso', 'Finalizado') NOT NULL,
  `Empleado_idEmpleado` INT(10) NOT NULL,
  `Lugar_idLugar` INT(10) NOT NULL,
  PRIMARY KEY (`idEvento`),
  CONSTRAINT `fk_Evento_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `gestion_evento`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Lugar1`
    FOREIGN KEY (`Lugar_idLugar`)
    REFERENCES `gestion_evento`.`Lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEvento_UNIQUE` ON `gestion_evento`.`Evento` (`idEvento` ASC);

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `gestion_evento`.`Evento` (`nombre` ASC);

CREATE INDEX `fk_Evento_Empleado1_idx` ON `gestion_evento`.`Evento` (`Empleado_idEmpleado` ASC);

CREATE INDEX `fk_Evento_Lugar1_idx` ON `gestion_evento`.`Evento` (`Lugar_idLugar` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Cliente` (
  `idCliente` INT(10) NOT NULL AUTO_INCREMENT,
  `cedula` BIGINT(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` BIGINT(10) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCliente_UNIQUE` ON `gestion_evento`.`Cliente` (`idCliente` ASC);

CREATE UNIQUE INDEX `cedula_UNIQUE` ON `gestion_evento`.`Cliente` (`cedula` ASC);

CREATE UNIQUE INDEX `correo_UNIQUE` ON `gestion_evento`.`Cliente` (`correo` ASC);

CREATE UNIQUE INDEX `telefono_UNIQUE` ON `gestion_evento`.`Cliente` (`telefono` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`Inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Inscripcion` (
  `idInscripcion` INT(10) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estado` ENUM('Por confirmar', 'Inscrito') NOT NULL,
  `asistencia` ENUM('Asistio', 'No asistio', 'Pendiente') NULL,
  `Evento_idEvento` INT(10) NOT NULL,
  `Cliente_idCliente` INT(10) NOT NULL,
  `Empleado_idEmpleado` INT(10) NOT NULL,
  PRIMARY KEY (`idInscripcion`),
  CONSTRAINT `fk_Inscripcion_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `gestion_evento`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `gestion_evento`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `gestion_evento`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idInscripción_UNIQUE` ON `gestion_evento`.`Inscripcion` (`idInscripcion` ASC);

CREATE INDEX `fk_Inscripcion_Empleado1_idx` ON `gestion_evento`.`Inscripcion` (`Empleado_idEmpleado` ASC);

CREATE INDEX `fk_Inscripcion_Cliente1_idx` ON `gestion_evento`.`Inscripcion` (`Cliente_idCliente` ASC);

CREATE INDEX `fk_Inscripcion_Evento1_idx` ON `gestion_evento`.`Inscripcion` (`Evento_idEvento` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Pago` (
  `idPago` INT(10) NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `estado` ENUM('Aceptado', 'En curso', 'Rechazado') NOT NULL,
  `Inscripcion_idInscripcion` INT(10) NOT NULL,
  PRIMARY KEY (`idPago`),
  CONSTRAINT `fk_Pago_Inscripcion1`
    FOREIGN KEY (`Inscripcion_idInscripcion`)
    REFERENCES `gestion_evento`.`Inscripcion` (`idInscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPago_UNIQUE` ON `gestion_evento`.`Pago` (`idPago` ASC);

CREATE INDEX `fk_Pago_Inscripcion1_idx` ON `gestion_evento`.`Pago` (`Inscripcion_idInscripcion` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`Conferencista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Conferencista` (
  `idConferencista` INT(10) NOT NULL AUTO_INCREMENT,
  `cedula` BIGINT(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` BIGINT(10) NOT NULL,
  PRIMARY KEY (`idConferencista`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idConferencista_UNIQUE` ON `gestion_evento`.`Conferencista` (`idConferencista` ASC);

CREATE UNIQUE INDEX `cedula_UNIQUE` ON `gestion_evento`.`Conferencista` (`cedula` ASC);

CREATE UNIQUE INDEX `telefono_UNIQUE` ON `gestion_evento`.`Conferencista` (`telefono` ASC);

CREATE UNIQUE INDEX `correo_UNIQUE` ON `gestion_evento`.`Conferencista` (`correo` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`Salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Salon` (
  `idSalon` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`idSalon`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idSalon_UNIQUE` ON `gestion_evento`.`Salon` (`idSalon` ASC);

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `gestion_evento`.`Salon` (`nombre` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`Conferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`Conferencia` (
  `idConferencia` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `Evento_idEvento` INT(10) NOT NULL,
  `Salon_idSalon` INT(10) NOT NULL,
  `Conferencista_idConferencista` INT(10) NOT NULL,
  `Empleado_idEmpleado` INT(10) NOT NULL,
  PRIMARY KEY (`idConferencia`),
  CONSTRAINT `fk_Conferencia_Conferencista1`
    FOREIGN KEY (`Conferencista_idConferencista`)
    REFERENCES `gestion_evento`.`Conferencista` (`idConferencista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conferencia_Salon1`
    FOREIGN KEY (`Salon_idSalon`)
    REFERENCES `gestion_evento`.`Salon` (`idSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conferencia_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `gestion_evento`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conferencia_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `gestion_evento`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idConferencia_UNIQUE` ON `gestion_evento`.`Conferencia` (`idConferencia` ASC);

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `gestion_evento`.`Conferencia` (`nombre` ASC);

CREATE INDEX `fk_Conferencia_Conferencista1_idx` ON `gestion_evento`.`Conferencia` (`Conferencista_idConferencista` ASC);

CREATE INDEX `fk_Conferencia_Salon1_idx` ON `gestion_evento`.`Conferencia` (`Salon_idSalon` ASC);

CREATE INDEX `fk_Conferencia_Empleado1_idx` ON `gestion_evento`.`Conferencia` (`Empleado_idEmpleado` ASC);

CREATE INDEX `fk_Conferencia_Evento1_idx` ON `gestion_evento`.`Conferencia` (`Evento_idEvento` ASC);


-- -----------------------------------------------------
-- Table `gestion_evento`.`MaterialConferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_evento`.`MaterialConferencia` (
  `idMaterialConferencia` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `Conferencia_idConferencia` INT(10) NOT NULL,
  PRIMARY KEY (`idMaterialConferencia`),
  CONSTRAINT `fk_MaterialConferencia_Conferencia1`
    FOREIGN KEY (`Conferencia_idConferencia`)
    REFERENCES `gestion_evento`.`Conferencia` (`idConferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMaterialConferencista_UNIQUE` ON `gestion_evento`.`MaterialConferencia` (`idMaterialConferencia` ASC);

CREATE INDEX `fk_MaterialConferencia_Conferencia1_idx` ON `gestion_evento`.`MaterialConferencia` (`Conferencia_idConferencia` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- 1.insert de la tabla Empleado
-- -----------------------------------------------------
INSERT INTO `empleado` (idEmpleado, cedula, nombre, apellido, telefono, correo, contraseña, tipoEmpleado)
VALUES (NULL, 1234567890, 'Daniela', 'Hernandez', 3213459731, 'daniela.hernandez@example.com', 'mypassword', 'AUTO');
INSERT INTO `empleado` (idEmpleado, cedula, nombre, apellido, telefono, correo, contraseña, tipoEmpleado)
VALUES (NULL, 1234567893, 'Juan', 'Pérez', 3201234567, 'juan.perez@example.com', 'mypassword', 'ADMIN');
INSERT INTO `empleado` (idEmpleado, cedula, nombre, apellido, telefono, correo, contraseña, tipoEmpleado)
VALUES (NULL, 1345678901, 'María', 'González',3209876543, 'maria.gonzalez@example.com', 'mipassword', 'ASESOR');

-- -----------------------------------------------------
-- 2.insert de la tabla Ciudad
-- -----------------------------------------------------
INSERT INTO `ciudad` (idCiudad, nombre)
VALUES (NULL, 'Bogota');
INSERT INTO `ciudad` (idCiudad, nombre)
VALUES (NULL, 'Medellin');
INSERT INTO `ciudad` (idCiudad, nombre) 
VALUES (NULL, 'Bucaramanga');
INSERT INTO `ciudad` (idCiudad, nombre)
VALUES (NULL, 'Neiva');
INSERT INTO `ciudad` (idCiudad, nombre) 
VALUES (NULL, 'Barranquilla');

-- -----------------------------------------------------
-- 3.insert de la tabla Lugar
-- -----------------------------------------------------
INSERT INTO `lugar` (idLugar, nombre, Ciudad_idCiudad)
VALUES (NULL, 'Coorferias', 1);
INSERT INTO `lugar`  (idLugar, nombre, Ciudad_idCiudad)
VALUES (NULL, 'Morguta', 2);
INSERT INTO `lugar`  (idLugar, nombre, Ciudad_idCiudad)
VALUES (NULL, 'San cardenas', 3);
INSERT INTO `lugar`  (idLugar, nombre, Ciudad_idCiudad)
VALUES (NULL, 'Hortua', 1);
INSERT INTO `lugar`  (idLugar, nombre, Ciudad_idCiudad)
VALUES (NULL, 'Senferino', 2);

-- -----------------------------------------------------
-- 4.insert de la tabla Evento
-- -----------------------------------------------------
INSERT INTO `evento` (idEvento, nombre, fechaInicio, horaInicio, fechaFin, horaFin, descripcion, costo, estado, Empleado_idEmpleado, Lugar_idLugar)
VALUES (NULL, 'Feria del Libro', '2023-08-01', '9:00', '2023-08-10', '12:00', 'Feria del libro de Buenos Aires', 250000.0, 'Por iniciar', 1, 2);
INSERT INTO `evento` (idEvento, nombre, fechaInicio, horaInicio, fechaFin, horaFin, descripcion, costo, estado, Empleado_idEmpleado, Lugar_idLugar)
VALUES (NULL, 'Expo Ferretera', '2023-09-01','8:00', '2023-09-04', '6:00', 'Exposición de herramientas', 250000.0, 'En curso', 1, 1);
INSERT INTO `evento` (idEvento, nombre, fechaInicio, horaInicio, fechaFin, horaFin, descripcion, costo, estado, Empleado_idEmpleado, Lugar_idLugar)
VALUES (NULL, 'Congreso de Medicina', '2023-10-15', '9:30', '2023-10-20', '5:00', 'Congreso de medicina Bogota', 250000.0, 'Por iniciar', 1, 3);

-- -----------------------------------------------------
-- 5.insert de la tabla Salon
-- -----------------------------------------------------
INSERT INTO `salon` (idSalon, nombre, capacidad)
VALUES (NULL, 'Salón Azul', 50);
INSERT INTO `salon` (idSalon, nombre, capacidad)
VALUES (NULL, 'Salón Rojo', 30);
INSERT INTO `salon` (idSalon, nombre, capacidad)
VALUES (NULL, 'Salón Verde', 70);
INSERT INTO `salon` (idSalon, nombre, capacidad)
VALUES (NULL, 'Salón Amarillo', 20);
INSERT INTO `salon` (idSalon, nombre, capacidad)
VALUES (NULL, 'Salón Morado', 40);

-- -----------------------------------------------------
-- 6.insert de la tabla Conferencista
-- -----------------------------------------------------
INSERT INTO `conferencista` (idConferencista, cedula, nombre, apellido, correo, telefono)
VALUES (NULL, 1234567890, 'Juan', 'Pérez', 'juan.perez@mail.com', 3115551231);
INSERT INTO `conferencista` (idConferencista, cedula, nombre, apellido, correo, telefono)
VALUES (NULL, 1876543210, 'María', 'González', 'maria.gonzalez@mail.com', 3115551232);
INSERT INTO `conferencista` (idConferencista, cedula, nombre, apellido, correo, telefono)
VALUES (NULL, 1357924680, 'Pedro', 'Martínez', 'pedro.martinez@mail.com', 3115551233);
INSERT INTO `conferencista` (idConferencista, cedula, nombre, apellido, correo, telefono)
VALUES (NULL, 1642015379, 'Ana', 'Ramírez', 'ana.ramirez@mail.com', 3115551234);
INSERT INTO `conferencista` (idConferencista, cedula, nombre, apellido, correo, telefono)
VALUES (NULL, 1468135790, 'Jorge', 'García', 'jorge.garcia@mail.com', 3115551235);

-- -----------------------------------------------------
-- 7.insert de la tabla Conferencia
-- -----------------------------------------------------
INSERT INTO `conferencia` (idConferencia, nombre, fecha, horaInicio, horaFin, Evento_idEvento, Salon_idSalon, Conferencista_idConferencista, Empleado_idEmpleado) 
VALUES (NULL, 'Conferencia de Tecnología', '2022-06-10', '10:00:00', '12:00:00', 1, 1, 1, 1);
INSERT INTO `conferencia` (idConferencia, nombre, fecha, horaInicio, horaFin, Evento_idEvento, Salon_idSalon, Conferencista_idConferencista, Empleado_idEmpleado) 
VALUES (NULL, 'Conferencia de Marketing Digital', '2022-06-12', '14:00:00', '16:00:00', 1, 2, 2, 1);
INSERT INTO `conferencia` (idConferencia, nombre, fecha, horaInicio, horaFin, Evento_idEvento, Salon_idSalon, Conferencista_idConferencista, Empleado_idEmpleado) 
VALUES (NULL, 'Conferencia de Diseño Gráfico', '2022-06-15', '11:00:00', '13:00:00', 2, 3, 3, 2);
INSERT INTO `conferencia` (idConferencia, nombre, fecha, horaInicio, horaFin, Evento_idEvento, Salon_idSalon, Conferencista_idConferencista, Empleado_idEmpleado) 
VALUES (NULL, 'Conferencia de Desarrollo Web', '2022-06-17', '09:00:00', '11:00:00', 2, 4, 4, 2);
INSERT INTO `conferencia` (idConferencia, nombre, fecha, horaInicio, horaFin, Evento_idEvento, Salon_idSalon, Conferencista_idConferencista, Empleado_idEmpleado) 
VALUES (NULL, 'Conferencia de Inteligencia Artificial', '2022-06-20', '15:00:00', '17:00:00', 3, 5, 5, 2);

-- -----------------------------------------------------
-- 8.insert de la tabla MaterialConferencia
-- -----------------------------------------------------
INSERT INTO `materialconferencia` (idMaterialConferencia, nombre, descripcion, Conferencia_idConferencia)
VALUES (NULL, 'Presentación', 'Material visual para la presentación', 1);
INSERT INTO `materialconferencia` (idMaterialConferencia, nombre, descripcion, Conferencia_idConferencia)
VALUES (NULL, 'Artículo sobre el tema', 'Artículo que profundiza en el tema', 2);
INSERT INTO `materialconferencia` (idMaterialConferencia, nombre, descripcion, Conferencia_idConferencia)
VALUES (NULL, 'Resumen', 'Resumen de los principales puntos', 5);
INSERT INTO `materialconferencia` (idMaterialConferencia, nombre, descripcion, Conferencia_idConferencia)
VALUES (NULL, 'Folleto informativo', 'Folleto que resume los temas tratados', 3);
INSERT INTO `materialconferencia` (idMaterialConferencia, nombre, descripcion, Conferencia_idConferencia)
VALUES (NULL, 'Infografía', 'Infografía visual que resume los puntos', 4);

-- -----------------------------------------------------
-- 9.insert de la tabla Cliente
-- -----------------------------------------------------
INSERT INTO `cliente` (idCliente, cedula, nombre, apellido, correo, telefono) 
VALUES (NULL,1234567580, 'Juan', 'Pérez', 'juan.perez@example.com', 3033033031);
INSERT INTO `cliente` (idCliente, cedula, nombre, apellido, correo, telefono) 
VALUES (NULL,1345676901, 'María', 'González', 'maria.gonzalez@example.com', 3033033032);
INSERT INTO `cliente` (idCliente, cedula, nombre, apellido, correo, telefono) 
VALUES (NULL,1456789012, 'Pedro', 'Ramírez', 'pedro.ramirez@example.com', 3033033033);
INSERT INTO `cliente` (idCliente, cedula, nombre, apellido, correo, telefono) 
VALUES (NULL,1567895123, 'Ana', 'Jiménez', 'ana.jimenez@example.com', 3033033034);
INSERT INTO `cliente` (idCliente, cedula, nombre, apellido, correo, telefono) 
VALUES (NULL,1678902234, 'Luis', 'Sánchez', 'luis.sanchez@example.com', 3033033035);

-- -----------------------------------------------------
-- 10.insert de la tabla Inscripcion
-- -----------------------------------------------------
INSERT INTO `inscripcion` (idInscripcion, fecha, hora, estado, Evento_idEvento, Cliente_idCliente, Empleado_idEmpleado) 
VALUES (NULL, '2022-08-15', '10:00:00', 'Por confirmar', 2, 1, 2);
INSERT INTO `inscripcion` (idInscripcion, fecha, hora, estado, Evento_idEvento, Cliente_idCliente, Empleado_idEmpleado)  
VALUES (NULL, '2022-09-01', '15:30:00', 'Por confirmar', 1, 2, 2);
INSERT INTO `inscripcion` (idInscripcion, fecha, hora, estado, Evento_idEvento, Cliente_idCliente, Empleado_idEmpleado)  
VALUES (NULL, '2022-10-10', '09:00:00', 'Inscrito', 2, 4, 2);
INSERT INTO `inscripcion` (idInscripcion, fecha, hora, estado, Evento_idEvento, Cliente_idCliente, Empleado_idEmpleado)  
VALUES (NULL, '2022-11-20', '13:45:00', 'Por confirmar', 1, 3, 2);
INSERT INTO `inscripcion` (idInscripcion, fecha, hora, estado, Evento_idEvento, Cliente_idCliente, Empleado_idEmpleado)  
VALUES (NULL, '2022-12-05', '18:00:00', 'Inscrito', 1, 5, 2);

-- -----------------------------------------------------
-- 11.insert de la tabla Pago
-- -----------------------------------------------------
INSERT INTO `pago` (idPago, monto, fecha, hora, estado, Inscripcion_idInscripcion) 
VALUES (NULL, 250000, '2023-05-16', '13:30:00', 'Aceptado', 1);
INSERT INTO `pago` (idPago, monto, fecha, hora, estado, Inscripcion_idInscripcion) 
VALUES (NULL, 250000, '2023-05-17', '09:45:00', 'En curso', 5);
INSERT INTO `pago` (idPago, monto, fecha, hora, estado, Inscripcion_idInscripcion) 
VALUES (NULL, 250000, '2023-05-18', '16:15:00', 'Aceptado', 2);
INSERT INTO `pago` (idPago, monto, fecha, hora, estado, Inscripcion_idInscripcion) 
VALUES (NULL, 250000, '2023-05-19', '11:30:00', 'En curso', 4);
INSERT INTO `pago` (idPago, monto, fecha, hora, estado, Inscripcion_idInscripcion) 
VALUES (NULL, 250000, '2023-05-20', '14:00:00', 'Rechazado', 3);